# docker-compose.yml
services:
  postgres:
    image: postgres:16
    environment:
     - POSTGRES_DB=${POSTGRES_NAME}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=${POSTGRES_DATABASE_URL}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev